SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE if EXISTS tranx_credit_note_new_reference_tbl;
CREATE TABLE tranx_credit_note_new_reference_tbl (
  id BIGINT AUTO_INCREMENT NOT NULL,
   outlet_id BIGINT NULL,
   branch_id BIGINT NULL,
   sundry_debtors_id BIGINT NULL,
   tranx_sales_return_invoice_id BIGINT NULL,
   transaction_status_id BIGINT NULL,
   fiscal_year_id BIGINT NULL,
   srno BIGINT NULL,
   creditnote_new_reference_no VARCHAR(255) NULL,
   round_off DOUBLE NULL,
   total_base_amount DOUBLE NULL,
   total_amount DOUBLE NULL,
   taxable_amount DOUBLE NULL,
   totalgst DOUBLE NULL,
   sales_discount_amount DOUBLE NULL,
   sales_discount_per DOUBLE NULL,
   total_sales_discount_amt DOUBLE NULL,
   additional_charges_total DOUBLE NULL,
   financial_year VARCHAR(255) NULL,
   source VARCHAR(255) NULL,
   transcation_date datetime NULL,
   narrations VARCHAR(255) NULL,
   created_at datetime NULL,
   created_by BIGINT NULL,
   status BIT(1) NOT NULL,
   adjustment_status VARCHAR(255) NULL,
   balance DOUBLE NULL,
   sales_invoice_id BIGINT NULL,
   sales_challan_id BIGINT NULL,
   receipt_id BIGINT NULL,
   CONSTRAINT pk_tranx_credit_note_new_reference_tbl PRIMARY KEY (id)
);

DROP TABLE if EXISTS tranx_credit_note_details_tbl;
CREATE TABLE tranx_credit_note_details_tbl (
  id BIGINT AUTO_INCREMENT NOT NULL,
   branch_id BIGINT NULL,
   outlet_id BIGINT NULL,
   sundry_debtors_id BIGINT NULL,
   transaction_status_id BIGINT NULL,
   ledger_id BIGINT NULL,
   tranx_creditnote_master_id BIGINT NULL,
   total_amount DOUBLE NULL,
   balance DOUBLE NOT NULL,
   adjusted_id BIGINT NULL,
   adjusted_source VARCHAR(255) NULL,
   type VARCHAR(255) NULL,
   ledger_type VARCHAR(255) NULL,
   created_at datetime NULL,
   created_by BIGINT NULL,
   status BIT(1) NOT NULL,
   adjustment_status VARCHAR(255) NULL,
   operations VARCHAR(255) NULL,
   paid_amt DOUBLE NULL,
   source VARCHAR(255) NULL,
   dr DOUBLE NOT NULL,
   cr DOUBLE NOT NULL,
   payment_method VARCHAR(255) NULL,
   payment_tranx_no VARCHAR(255) NULL,
   transaction_date datetime NULL,
   payable_amt DOUBLE NULL,
   selected_amt DOUBLE NULL,
   remaining_amt DOUBLE NULL,
   is_advance BIT(1) NULL,
   bank_name VARCHAR(255) NULL,
   payment_date datetime NULL,
   CONSTRAINT pk_tranx_credit_note_details_tbl PRIMARY KEY (id)
);
SET FOREIGN_KEY_CHECKS = 1;