SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE if EXISTS tranx_sales_comp_invoice_tbl;
CREATE TABLE tranx_sales_comp_invoice_tbl (
  id BIGINT AUTO_INCREMENT NOT NULL,
   branch_id BIGINT NULL,
   outlet_id BIGINT NULL,
   sundry_debtors_id BIGINT NULL,
   sales_account_ledger_id BIGINT NULL,
   sales_discount_ledger_id BIGINT NULL,
   sales_round_off_id BIGINT NULL,
   associate_groups_id BIGINT NULL,
   fiscal_year_id BIGINT NULL,
   sales_serial_number BIGINT NULL,
   sales_invoice_no VARCHAR(255) NULL,
   bill_date datetime NULL,
   transport_name VARCHAR(255) NULL,
   reference VARCHAR(255) NULL,
   round_off DOUBLE NULL,
   total_base_amount DOUBLE NULL,
   total_amount DOUBLE NULL,
   totalcgst DOUBLE NULL,
   totalqty BIGINT NULL,
   totalsgst DOUBLE NULL,
   totaligst DOUBLE NULL,
   sales_discount_amount DOUBLE NULL,
   sales_discount_per DOUBLE NULL,
   total_sales_discount_amt DOUBLE NULL,
   additional_charges_total DOUBLE NULL,
   taxable_amount DOUBLE NULL,
   tcs DOUBLE NULL,
   is_counter_sale BIT(1) NULL,
   counter_sale_id VARCHAR(255) NULL,
   status BIT(1) NULL,
   financial_year VARCHAR(255) NULL,
   narration VARCHAR(255) NULL,
   operations VARCHAR(255) NULL,
   reference_sq_id VARCHAR(255) NULL,
   reference_so_id VARCHAR(255) NULL,
   reference_sc_id VARCHAR(255) NULL,
   created_by BIGINT NULL,
   payment_mode VARCHAR(255) NULL,
   payment_amount DOUBLE NULL,
   cash DOUBLE NULL,
   digital DOUBLE NULL,
   card_payment DOUBLE NULL,
   advanced_amount DOUBLE NULL,
   gst_number VARCHAR(255) NULL,
   created_at datetime NULL,
   updated_by BIGINT NULL,
   updated_at datetime NULL,
   balance DOUBLE NULL,
   addition_ledger1id BIGINT NULL,
   addition_ledger2id BIGINT NULL,
   addition_ledger3id BIGINT NULL,
   addition_ledger_amt1 DOUBLE NULL,
   addition_ledger_amt2 DOUBLE NULL,
   addition_ledger_amt3 DOUBLE NULL,
   free_qty DOUBLE NULL,
   gross_amount DOUBLE NULL,
   total_tax DOUBLE NULL,
   salesman_id BIGINT NULL,
   barcode VARCHAR(255) NULL,
   salesman_user BIGINT NULL,
   transaction_status BIGINT NULL,
   is_selected BIT(1) NULL,
   is_credit_note_ref BIT(1) NULL,
   is_round_off BIT(1) NULL,
   tcs_amt DOUBLE NULL,
   tcs_mode VARCHAR(255) NULL,
   tds_amt DOUBLE NULL,
   tds_per DOUBLE NULL,
   image_path VARCHAR(255) NULL,
   CONSTRAINT pk_tranx_sales_comp_invoice_tbl PRIMARY KEY (id)
);


DROP TABLE if EXISTS tranx_sales_comp_details_units_tbl;
CREATE TABLE tranx_sales_comp_details_units_tbl (
  id BIGINT AUTO_INCREMENT NOT NULL,
   sales_invoice_id BIGINT NULL,
   sales_invoice_details_id BIGINT NULL,
   product_id BIGINT NULL,
   units_id BIGINT NULL,
   packing_master_id BIGINT NULL,
   flavour_master_id BIGINT NULL,
   product_batch_no_id BIGINT NULL,
   brand_id BIGINT NULL,
   group_id BIGINT NULL,
   category_id BIGINT NULL,
   subcategory_id BIGINT NULL,
   transaction_status_id BIGINT NULL,
   unit_conversions DOUBLE NULL,
   qty DOUBLE NULL,
   rate DOUBLE NULL,
   base_amt DOUBLE NULL,
   total_amount DOUBLE NULL,
   discount_amount DOUBLE NULL,
   discount_per DOUBLE NULL,
   discount_amount_cal DOUBLE NULL,
   discount_per_cal DOUBLE NULL,
   igst DOUBLE NULL,
   sgst DOUBLE NULL,
   cgst DOUBLE NULL,
   total_igst DOUBLE NULL,
   total_sgst DOUBLE NULL,
   total_cgst DOUBLE NULL,
   final_amount DOUBLE NULL,
   created_at datetime NULL,
   created_by BIGINT NULL,
   updated_at datetime NULL,
   updated_by BIGINT NULL,
   status BIT(1) NULL,
   free_qty DOUBLE NULL,
   discountbin_per DOUBLE NULL,
   total_discount_in_amt DOUBLE NULL,
   gross_amt DOUBLE NULL,
   addition_charges_amt DOUBLE NULL,
   gross_amt1 DOUBLE NULL,
   invoice_dis_amt DOUBLE NULL,
   levelaid BIGINT NULL,
   levelbid BIGINT NULL,
   levelcid BIGINT NULL,
   return_qty DOUBLE NULL,
   CONSTRAINT pk_tranx_sales_comp_details_units_tbl PRIMARY KEY (id)
);

DROP TABLE if EXISTS tranx_sales_comp_duties_taxes_tbl;
CREATE TABLE tranx_sales_comp_duties_taxes_tbl (
  id BIGINT AUTO_INCREMENT NOT NULL,
   sales_transaction_id BIGINT NULL,
   sundry_debtors_id BIGINT NULL,
   duties_taxes_id BIGINT NULL,
   intra BIT(1) NULL,
   amount DOUBLE NULL,
   status BIT(1) NULL,
   created_at datetime NULL,
   created_by BIGINT NULL,
   CONSTRAINT pk_tranx_sales_comp_duties_taxes_tbl PRIMARY KEY (id)
);

DROP TABLE if EXISTS tranx_sales_comp_addi_charges_tbl;
CREATE TABLE tranx_sales_comp_addi_charges_tbl (
  id BIGINT AUTO_INCREMENT NOT NULL,
   sales_transaction_id BIGINT NULL,
   additional_charges_id BIGINT NULL,
   amount DOUBLE NULL,
   created_at datetime NULL,
   created_by BIGINT NULL,
   status BIT(1) NULL,
   operation VARCHAR(255) NULL,
   CONSTRAINT pk_tranx_sales_comp_addi_charges_tbl PRIMARY KEY (id)
);

DROP TABLE if EXISTS tranx_sales_comp_pr_sr_no_tbl;
CREATE TABLE tranx_sales_comp_pr_sr_no_tbl (
  id BIGINT AUTO_INCREMENT NOT NULL,
   branch_id BIGINT NULL,
   outlet_id BIGINT NULL,
   product_id BIGINT NULL,
   transaction_type_master_id BIGINT NULL,
   serial_no VARCHAR(255) NULL,
   sale_created_at datetime NULL,
   transaction_status VARCHAR(255) NULL,
   operations VARCHAR(255) NULL,
   created_by BIGINT NULL,
   created_at datetime NULL,
   updated_by BIGINT NULL,
   updated_at datetime NULL,
   status BIT(1) NULL,
   levelaid BIGINT NULL,
   levelbid BIGINT NULL,
   levelcid BIGINT NULL,
   tranx_sales_invoice_details_units_id BIGINT NULL,
   units_id BIGINT NULL,
   CONSTRAINT pk_tranx_sales_comp_pr_sr_no_tbl PRIMARY KEY (id)
);
SET FOREIGN_KEY_CHECKS = 1;