ALTER TABLE product_tbl
ADD COLUMN ecommerce_type_id BIGINT NULL,
ADD COLUMN selling_price DOUBLE NULL,
ADD COLUMN discount_per DOUBLE NULL,
ADD COLUMN amount DOUBLE NULL,
ADD COLUMN loyalty DOUBLE NULL,
ADD COLUMN image1 VARCHAR(255) NULL,
ADD COLUMN image2 VARCHAR(255) NULL,
ADD COLUMN image3 VARCHAR(255) NULL,
ADD COLUMN image4 VARCHAR(255) NULL,
ADD COLUMN image5 VARCHAR(255) NULL;